# NumPy Shapes & Dimensions

## Objective

Understand dimensions, shapes and metadata of NumPy arrays.

In [1]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])

arr

array([10, 20, 30, 40, 50])

In [4]:
print("Dimension :", arr.ndim)

print("Shape :", arr.shape)

print("Size :", arr.size)

print("Data Type :", arr.dtype)

Dimension : 1
Shape : (5,)
Size : 5
Data Type : int64


In [5]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print("Dimension :", matrix.ndim)

print("Shape :", matrix.shape)

print("Size :", matrix.size)

print("Data Type :", matrix.dtype)

Dimension : 2
Shape : (2, 3)
Size : 6
Data Type : int64


In [ ]:
cube = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

cube

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
print("Dimension :", cube.ndim)

print("Shape :", cube.shape)

print("Size :", cube.size)

print("Data Type :", cube.dtype)

Dimension : 3
Shape : (2, 2, 2)
Size : 8
Data Type : int64


In [11]:
print(type(cube))

<class 'numpy.ndarray'>


## Observation

- ndim → number of dimensions
- shape → size of each dimension
- size → total number of elements
- dtype → data type