# NumPy Indexing & Slicing

## Objective

Learn how to access data from NumPy arrays.

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [3]:
print(arr[0])

print(arr[2])

print(arr[-1])

10
30
50


In [4]:
print(arr[1:4])

[20 30 40]


In [5]:
print(arr[:3])

print(arr[2:])

print(arr[:])

[10 20 30]
[30 40 50]
[10 20 30 40 50]


In [8]:
print(arr[::2])

[10 30 50]


In [9]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
print(matrix[0,1])

print(matrix[2,2])

20
90


In [11]:
print(matrix[:,1])

[20 50 80]


In [12]:
print(matrix[1,:])

[40 50 60]


In [13]:
print(matrix[0:2,1:3])

[[20 30]
 [50 60]]
