# NumPy Indexing & Slicing

## Objective

Learn how to access data from NumPy arrays.

In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [4]:
print(arr[0])

print(arr[2])

print(arr[-1])

10
30
50


In [5]:
print(arr[1:4])

[20 30 40]


In [6]:
print(arr[:3])

print(arr[2:])

print(arr[:])

[10 20 30]
[30 40 50]
[10 20 30 40 50]


In [7]:
print(arr[::2])

[10 30 50]


In [8]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
print(matrix[0,1])

print(matrix[2,2])

20
90


In [10]:
print(matrix[:,1])

[20 50 80]


In [11]:
print(matrix[1,:])

[40 50 60]


In [12]:
print(matrix[0:2,1:3])

[[20 30]
 [50 60]]


Create

    [85,90,88]
    [78,81,79]
    [92,95,94]


Print

1. First row
2. Second column
3. Last row
4. First two rows
5. Last two columns

In [13]:
scores = np.array([ 
                [85,90,88],
                [78,81,79],
                [92,95,94]])

scores

array([[85, 90, 88],
       [78, 81, 79],
       [92, 95, 94]])

In [14]:
print(scores[0,:])

[85 90 88]


In [15]:
print(scores[:,1])

[90 81 95]


In [16]:
print(scores[-1,:])

[92 95 94]


In [17]:
print(scores[:2,:])

[[85 90 88]
 [78 81 79]]


In [18]:
print(scores[:,1:3])

[[90 88]
 [81 79]
 [95 94]]
