# NumPy Vectorization

## Objective

Learn how NumPy performs operations without loops.

In [60]:
import numpy as np

In [61]:
arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [62]:
arr * 2

array([ 20,  40,  60,  80, 100])

In [63]:
arr / 10

array([1., 2., 3., 4., 5.])

In [64]:
arr ** 2

array([ 100,  400,  900, 1600, 2500])

In [65]:
a = np.array([1,2,3])

b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [66]:
a * b

array([ 4, 10, 18])

In [67]:
numbers = [1,2,3]

print(numbers * 2)

[1, 2, 3, 1, 2, 3]


In [68]:
arr = np.array([1,2,3])

print(arr * 2)

[2 4 6]


⭐ Biggest Beginner Mistake

Many people think this:

arr * arr

means matrix multiplication.

It doesn't.

It means:

Element-wise multiplication

In [69]:
arr * arr

array([1, 4, 9])

Without using a loop:

Add 5 bonus marks.

Multiply every mark by 2.

Square every mark.

Divide every mark by 10.

In [70]:
marks = np.array([55,68,72,90,81])
