# NumPy Reshape

## Objective

Learn how to reshape arrays.

In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5,6])

arr

array([1, 2, 3, 4, 5, 6])

In [11]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix = arr.reshape(2,3)

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
matrix = matrix.flatten()

In [18]:
matrix.shape

(6,)

In [19]:
matrix.size

6

In [20]:
numbers = np.array([10,20,30,40,50,60,70,80])

In [25]:
numbers = numbers.reshape(4,2)

numbers

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [28]:
numbers = numbers.reshape(2,-1)

numbers

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [31]:
numbers = numbers.flatten()

numbers

array([10, 20, 30, 40, 50, 60, 70, 80])

In [33]:
numbers.size

8

In [34]:
numbers.shape

(8,)